# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tool

default_platform(:android)

platform :android do
  desc "Build Android debug APK for development"
  lane :dev_build do
    gradle(task: "clean assembleRelease", project_dir: "./android", properties: {
      "android.injected.signing.store.file" => "#{Dir.pwd}/../credentials/android/release.keystore",
      "android.injected.signing.store.password" => ENV['ANDROID_KEYSTORE_PASSWORD'],
      "android.injected.signing.key.alias" => ENV['ANDROID_KEY_ALIAS'],
      "android.injected.signing.key.password" => ENV['ANDROID_KEY_PASSWORD']
    })
  end

  desc "Submit a new internal test build to play store"
  lane :qa_release do
    previous_build_number = google_play_track_version_codes(
      track: "internal",
      json_key: "credentials/android/google-play-service-key.json"
    )[0]

    increment_version_name(
      gradle_file_path: "android/app/build.gradle"
    )
    increment_version_code(
      gradle_file_path: "android/app/build.gradle",
      version_code: previous_build_number + 1
    )

    gradle(task: "clean bundleRelease", project_dir: "./android", properties: {
      "android.injected.signing.store.file" => "#{Dir.pwd}/../credentials/android/release.keystore",
      "android.injected.signing.store.password" => ENV['ANDROID_KEYSTORE_PASSWORD'],
      "android.injected.signing.key.alias" => ENV['ANDROID_KEY_ALIAS'],
      "android.injected.signing.key.password" => ENV['ANDROID_KEY_PASSWORD']
    })

    upload_to_play_store(
      track: 'internal',
      json_key: "credentials/android/google-play-service-key.json",
      aab: "android/app/build/outputs/bundle/release/app-release.aab"
    )

    changelog_from_git_commits
  end

  desc "Submit a new staging build to play store"
  lane :stg_release do
    increment_version_name(
      gradle_file_path: "android/app/build.gradle"
    )
    increment_version_code(
      gradle_file_path: "android/app/build.gradle"
    )

    gradle(task: "clean bundleRelease", project_dir: "./android", properties: {
      "android.injected.signing.store.file" => "#{Dir.pwd}/../credentials/android/release.keystore",
      "android.injected.signing.store.password" => ENV['ANDROID_KEYSTORE_PASSWORD'],
      "android.injected.signing.key.alias" => ENV['ANDROID_KEY_ALIAS'],
      "android.injected.signing.key.password" => ENV['ANDROID_KEY_PASSWORD']
    })

    upload_to_play_store(
      track: 'closed',
      json_key: "credentials/android/google-play-service-key.json",
      aab: "android/app/build/outputs/bundle/release/app-release.aab"
    )

    changelog_from_git_commits
  end

  desc "Submit a new production build to play store"
  lane :production_release do
    increment_version_name(
      gradle_file_path: "android/app/build.gradle"
    )
    increment_version_code(
      gradle_file_path: "android/app/build.gradle"
    )

    gradle(task: "clean bundleRelease", project_dir: "./android", properties: {
      "android.injected.signing.store.file" => "#{Dir.pwd}/../credentials/android/release.keystore",
      "android.injected.signing.store.password" => ENV['ANDROID_KEYSTORE_PASSWORD'],
      "android.injected.signing.key.alias" => ENV['ANDROID_KEY_ALIAS'],
      "android.injected.signing.key.password" => ENV['ANDROID_KEY_PASSWORD']
    })

    upload_to_play_store(
      track: 'production',
      release_status: "draft",
      json_key: "credentials/android/google-play-service-key.json",
      aab: "android/app/build/outputs/bundle/release/app-release.aab"
    )
  end
end

platform :ios do
  # Explicitly select Xcode version to avoid conflicts with multiple Xcode installations
  # xcode_select "/Applications/Xcode16.app"

  desc "Build iOS simulator app for development"
  lane :dev_build do
    build_ios_app(
      workspace: "ios/smbmobile.xcworkspace",
      scheme: "smbmobile",
      sdk: "iphonesimulator",
      configuration: "Debug",
      derived_data_path: "ios/build",
      output_directory: "ios/build",
      output_name: "smbmobile.app"
    )
  end

  desc "Submit a new QA build to TestFlight"
  lane :qa_release do
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
      key_filepath: "#{Dir.pwd}/../credentials/ios/AuthKey.p8"
    )

    match(
      type: "appstore",
      readonly: true,
      app_identifier: "com.insighture.smbmobile",
      git_url: "git@github.com:insighture/smb-mobile-fastlane.git",
      api_key: api_key,
      force_for_new_devices: true
    )

    # ✅ Fix for versioning
    increment_version_number(
      xcodeproj: "ios/smbmobile.xcodeproj",
      bump_type: "patch"
    )
    increment_build_number(
      xcodeproj: "ios/smbmobile.xcodeproj"
    )

    build_ios_app(
      workspace: "ios/smbmobile.xcworkspace",
      scheme: "smbmobile",
      clean: true,
      output_directory: "ios/build",
      derived_data_path: "ios/build/DerivedData",
      export_method: "app-store",
      sdk: "iphoneos",
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          "com.insighture.smbmobile" => "match AppStore com.insighture.smbmobile"
        }
      },
      output_name: "smbmobile.ipa",
      verbose: true,
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )

    changelog_from_git_commits
  end

  desc "Submit a new staging build to TestFlight"
  lane :stg_release do
    increment_version_number(
      xcodeproj: "ios/smbmobile.xcodeproj",
      bump_type: "patch"
    )
    increment_build_number(
      xcodeproj: "ios/smbmobile.xcodeproj"
    )

    build_ios_app(
      workspace: "ios/smbmobile.xcworkspace",
      scheme: "smbmobile",
      export_method: "app-store",
      sdk: "iphoneos",
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          "com.insighture.smbmobile" => "match AppStore com.insighture.smbmobile"
        }
      },
      output_directory: "ios/build",
      output_name: "smbmobile.ipa"
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )

    changelog_from_git_commits
  end

  desc "Submit a new production build to App Store"
  lane :production_release do
    increment_version_number(
      xcodeproj: "ios/smbmobile.xcodeproj",
      bump_type: "patch"
    )
    increment_build_number(
      xcodeproj: "ios/smbmobile.xcodeproj"
    )

    build_ios_app(
      workspace: "ios/smbmobile.xcworkspace",
      scheme: "smbmobile",
      export_method: "app-store",
      sdk: "iphoneos",
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          "com.insighture.smbmobile" => "match AppStore com.insighture.smbmobile"
        }
      },
      output_directory: "ios/build",
      output_name: "smbmobile.ipa"
    )

    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false
    )

    changelog_from_git_commits
  end

  desc "Submit a new production build to App Store (legacy)"
  lane :release do
    increment_version_number(
      xcodeproj: "ios/smbmobile.xcodeproj",
      bump_type: "patch"
    )
    increment_build_number(
      xcodeproj: "ios/smbmobile.xcodeproj"
    )

    build_ios_app(
      workspace: "ios/smbmobile.xcworkspace",
      scheme: "smbmobile",
      export_method: "app-store",
      sdk: "iphoneos",
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          "com.insighture.smbmobile" => "match AppStore com.insighture.smbmobile"
        }
      },
      output_directory: "ios/build",
      output_name: "smbmobile.ipa"
    )

    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false
    )

    changelog_from_git_commits
  end
end
